### ISSUE TITLE
Copy comments to article's talk page when accepting

### ISSUE THREAD

**Issue by enterprisey** [wikimedia-gadgets/afc-helper#128]
Very long-standing request.

> Second, when [a] draft is accepted, would it be possible to copy the AFC comments to the talk page, or to give the reviewer the option of copying them to the talk page? Sometimes they call for improvements to the article, and sometimes they call for improvements to another article (such as including the name of the subject of the article in a disambiguation list of people with the same name).

Requested by Robert McClenon on 04:00, 27 October 2020 (UTC)
Archive link: https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation/2020_4#Script_Addition_Requests

**Comment by primefac** [comment]
Automatic, no; quite often the comments are nothing more than indicating what needs improving.

**Comment by enterprisey** [comment]
The advanced version of this would probably be a checkbox UI showing a list of all the comments and checkboxes specifying whether to copy over each one. Quite possibly not worth the additional effort, though.

**Comment by primefac** [comment]
That's an interesting idea! I do think it would likely be more hassle than it's worth, though; the comments are (if I understand those who want this done) being kept mainly for historical reasons over any sort of "ongoing discussion" concerns.

**Comment by robertsky** [comment]
if implemented, when copying over to the talk page, the Afc comment template should be subst as well. No point leaving them encapsulated when it is in the talk page for historical purposes.

**Comment by primefac** [comment]
Agreed with the subst. This might be an obvious statement, but they should probably be in a new section as well, with the header being something like "Pre-accept reviewer comments" or something similar, to indicate their provenance.

**Comment by NovemLinguae** [comment]
Mentioned by Robert McClenon at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Move_AFC_Comments_to_Talk_Page_on_Acceptance

**Comment by NovemLinguae** [comment]
> I do think it would likely be more hassle than it's worth, though

Looks like Primefac has updated their opinion a bit. Here's the latest:

> I'm going to add in ''my'' perennial reply to this request that if/when this is implemented (which for the record, I generally support) it should be opt-in (i.e. check-boxed), as I rarely find reason to keep the comments left by reviewers.

**Comment by primefac** [comment]
I would argue that's the same opinion, just worded differently ;-)

I don't know if I've ever been really "opposed" to this suggestion, just (per the latter part of the latter quote) don't really see the use in most cases.
