### ISSUE TITLE
When declining, error if no reason is selected

### ISSUE THREAD

**Issue by earwig** [wikimedia-gadgets/afc-helper#145]
I made [this silly mistake](https://en.wikipedia.org/w/index.php?title=Draft:Venge.io&diff=prev&oldid=1008431960) because I didn't select anything from the reason dropdown, resulting in `undefined`. The script should refuse to continue without a reason selected, and maybe even suggest "custom" if I've written some freeform text.

**Comment by enterprisey** [comment]
Proposed solution: decline (reject) button should gray out and change text to "please select a decline (reject) reason".

**Comment by Adityachaturvedi2906** [comment]
Hey, @enterprisey This bug looks interesting, so it's my request to assign me this bug and guide me on the same.

**Comment by imyashl** [comment]
Hey @enterprisey, I would like to work on this issue, can you please guide me further on the same?

**Comment by enterprisey** [comment]
@Adityachaturvedi2906 sure, done. @imyashl I have recently added the good-first-issue tag to #106 and #156; feel free to pick one of them. 106 is harder but more interesting.

**Comment by NovemLinguae** [comment]
Tested, works. #177 fixed this. Closing.
