### ISSUE TITLE
Linking to the next submission in the queue

### ISSUE THREAD

**Issue by enterprisey** [wikimedia-gadgets/afc-helper#19]
I was thinking about replicating [#204](https://github.com/WPAFC/afch/issues/204) from the non-rewrite repo. Should I put [`afcHelper_getNextPage()`](https://github.com/WPAFC/afch/commit/3790ff6fd3abdd433c204cdb4284dc6578e840aa#diff-c5875c2def917a84e0fc1ac19e571d81R1725) in the submissions module or somewhere else?

(This is one of the features from the non-rewrite version which I miss the most.)

**Comment by APerson241** [comment]
(For posterity: as the fix from #21 eventually failed due to changes in the API, a permanent solution was found with #33.)
