### ISSUE TITLE
Automatically add {{Uncategorized}} and {{Improve categories}}

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#220]
Definitely: automatically add {{Uncategorized}} if in 0 categories. I think it is safe to assume that every article can be placed in at least 1 category.

Maybe: automatically add {{Improve categories}} if in 1 category. If you agree that it is safe to assume that most articles can be placed in 2 or more categories. Alternatively, could add a check box for this to the accept form.

Where do these tags go? It's not mentioned in MOS:ORDER, but I think we can copy Twinkle to get an idea of where this should go. Twinkle places category maintenance tags after stubs (basically at the very bottom)

**Comment by NovemLinguae** [comment]
Mentioned by Robert McClenon at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Acceptance_by_the_script%2C_categories%2C_and_a_tag_check_box%3F

Specifically, he requested that there be a check box added to the accept form to place {{Improve categories}}

**Comment by NovemLinguae** [comment]
Mentioned in Discord by asilvering today. Suggested a check box for "uncategorized"

**Comment by primefac** [comment]
I disagree with this; there is zero reason the reviewer cannot add at _least_ one category. If anything, we should make it a mandatory part of the AFCH process.

**Comment by NovemLinguae** [comment]
Sorry, have to decline this one. The discussion at WT:AFC did not achieve consensus for this feature.
