### ISSUE TITLE
Button to add {{AfC submission|T}} to pages in draftspace that don't have it yet

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#240]
Should probably add it as an option to the "Submit" dropdown, perhaps named "Unsubmitted". Would place `{{AfC submission|T}}`, which is the unsubmitted state.

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/79697282/179370760-d107a933-d01e-4c9b-9287-0bee6543612d.png">

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/79697282/179370766-2932b0a7-a6e7-46cd-9596-bd96b03d5a74.png">

**Comment by primefac** [comment]
"Should probably add it as an option " - why?

**Comment by NovemLinguae** [comment]
My use case was today there was someone in Discord that made a draft without an `{{AfC submission|T}}` template. I want to be able to easily add this to their draft without submitting it before they are ready. `{{AfC submission|T}}` is hard to memorize.

**Comment by primefac** [comment]
{{AFC submission/draft}} is pretty easy to remember...

**Comment by primefac** [comment]
(forgive the snark, it is late and Scotland just lost to Argentina)

**Comment by primefac** [comment]
If you think this is worthwhile, feel free, but please don't add in a timestamp, because when it *does* get submitted, it is incredibly likely to immediately throw the page into Very Old

**Comment by NovemLinguae** [comment]
Abandoning. Received pushback.

**Comment by NovemLinguae** [comment]
Reopening due to renewed interest at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Template%3AAfC_submission%2Fdraft. Will see how that discussion shakes out then make a decision about this issue.
