### ISSUE TITLE
Handle accepting over redirect with non-trivial history

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#243]
Suggested by Naraht at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#db-afc-move_info_in_template

AFCH should detect if a redirect with more than one revision is in the way of an accept. If so, it should ask the reviewer if they want to place a {{Db-afc-move}} tag on the mainspace redirect page. Current behavior is to block acceptance completely by disabling buttons.

Acceptance criteria
* [ ] Detect a redirect with non-trivial history
* [ ] Notify the user and ask the user yes/no if they want to place {{Db-afc-move}}
* [ ] Place {{Db-afc-move}} on redirect page
* [ ] Mark the current draft as "Under review"

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/79697282/184236196-004f843c-6525-4108-b98f-f9fd0da6cf12.png">

**Comment by NovemLinguae** [comment]
This is a perennial issue at the WT:AFC talk page. The frequency that this question gets asked is like 5+ times a year.

We should prioritize building automatic {{Db-afc-move}} tagging of redirects into AFC. Or at least a yes/no prompt to the reviewer asking if they want to place the tag.

-OR-

Instead of using the {{Db-afc-move}} tag, we could ask the reviewer if they want to make an entry at WP:RM/TR. The disadvantage of this is that some of the cleanup and talk page tags doesn't get done. The advantage of this is the reviewer doesn't have to remember to come back and re-accept the page later.

The disadvantage could be countered by prepping the article for mainspace with the script anyway even though it's still in draftspace, e.g. run wikitext cleanup, place categories, place WikiProject tags, etc.

**Comment by primefac** [comment]
I disagree rather strongly with the second proposal, as it was the reason why I created the db- template in the first place - if we want a reviewer to accept it, using the script, and doing everything "right first time", then the reviewer should be the one moving the page.

That being said we _really_ need to encourage people waiting for the redirect to be deleted to mark the page as "under review" so super-picky admins (I am _not_ going to name names here) will know that the page actually is being reviewed and not bitch that _they_ have to move it (or some nonsense).

**Comment by NovemLinguae** [comment]
Sounds good. Let's move forward with a patch that detects a redirect with non-trivial history is in the way, and asks the user yes/no if they want to place {{Db-afc-move}}

We could have the script also automatically mark the page as under review when placing {{Db-afc-move}}

**Comment by NovemLinguae** [comment]
Confusion over {{Db-afc-move}} is mentioned constantly (multiple times a year) at WT:AFC. Would help to build this into AFCH. Latest mention: https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:WikiProject_Articles_for_creation&curid=11547670&diff=1211557439&oldid=1211451299
