### ISSUE TITLE
Regex catastrophic backtracking when h2 followed by 100 spaces

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#245]
Steps to reproduce
* Create Draft:Test somewhere
* Edit the page so that this is the wikitext (thanks KylieTastic for this)
````
{{AFC submission}}
==A==
                                                                                                             
B
````
* Load the page, load AFCH
* Open DevTools real quick, before the page gets too busy
* Hit the pause and play buttons a few times to see what spot the code is stuck in. You'll find it's stuck here:
https://github.com/WPAFC/afch-rewrite/blob/5ba43d26ffa1cf4177119619c0e85c56b39f9290/src/modules/submissions.js#L556-L558
* Copy paste the above test case and the above regex into https://regex101.com/r/SN64cV/1
* It throws catastrophic backtracking error

What happens?
* Page freezes due to being busy in endless loop.

What should have happened?
* Normal operation. Page remains responsive. AFCH remains responsive.

**Comment by fee1-dead** [comment]
I think this one needs an iterative approach to replace the regex by repeatedly stripping ending `[[:?Category:.+?]]` and whitespace from the text and see if the result becomes a section header. `"==.+?=="`. That will improve the efficiency here.

**Comment by siddharthvp** [comment]
Also, we should set up CodeQL that detects such security issues.

**Comment by NovemLinguae** [comment]
Reported again today at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Article_causing_tab_to_hang

**Comment by NovemLinguae** [comment]
Reported again today at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Can't_decline_an_article%3F

Article is https://en.wikipedia.org/wiki/Draft:2026_Israeli_legislative_election

Regex is https://regex101.com/r/AEk6Kx/1

**Comment by KylieTastic** [comment]
@NovemLinguae, the new version #[5e7e3b9](https://github.com/NovemLinguae/afch-rewrite/commit/5e7e3b9ff3790d2a9651a62419dcbf84175bc5b9) does not match the test on https://regex101.com/r/AEk6Kx/1 you;ve dropped the :? before the Category

**Comment by NovemLinguae** [comment]
Fixed. Thanks KylieTastic.

**Comment by NovemLinguae** [comment]
Reported again today: https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Glitch
