### ISSUE TITLE
Custom reason for rejects

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#250]
Requested by AngusWOOF off-wiki

When declining, you can choose a custom reason

<img width="751" alt="image" src="https://user-images.githubusercontent.com/79697282/202284891-655f7445-e0ea-49ef-8aa9-b9a375719e5a.png">

This is a feature request to also allow this for rejecting

**Comment by primefac** [comment]
I know I've said this on a few recent feature requests, but I think this would be good to discuss on-wiki; do we need custom reasons for rejection, or just more/"better" reasons for rejection?

**Comment by enterprisey** [comment]
Concur, FWIW, that it would be nice to have an onwiki discussion. The existence of the request means that there are some potential use-cases for this feature, but I'd rather those use-cases be discussed where WPAFC members can comment on them, to verify the extent to which we need this. I suspect there's potential for negative impact on the submitter experience here
