### ISSUE TITLE
remove version number

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#270]
![image](https://github.com/wikimedia-gadgets/afch-rewrite/assets/79697282/4be4c8ab-fab3-49b9-a784-fdc1291b6c68)

Just one more thing for developers to forget to update. Any objections to removing the version number from the codebase, edit summaries, etc?

**Comment by primefac** [comment]
Fine by me.

**Comment by NovemLinguae** [comment]
Looks like https://github.com/wikimedia-gadgets/afch-rewrite/blob/master/scripts/release.py does a bunch of version stuff automatically, such as bumping the version variable. Supposedly.

"0.9.1 Imperial Ibex (05 December 2018)", the current version, says December 2018, but I know we've deployed a couple times since then.

Also git + GitHub version tagging is not occurring consistently. Says we're still on 0.9 from Nov 2014.

<img width="155" alt="image" src="https://github.com/wikimedia-gadgets/afch-rewrite/assets/79697282/94239772-fbf2-486a-91b4-e1f54619179e">

@enterprisey, when you deploy, do you use the release.py script? Maybe it's broken in regards to bumping the version number.

**Comment by siddharthvp** [comment]
Support. Version numbers in edit summary only tends to confuse folks. I've seen multiple times people misunderstanding 0.9.1 to some kind of rating given to the draft.

Note the release.py script doesn't do any on-wiki deployment - it's just for updating the version number, so unused since 2018. GitHub UI would only show releases created via GitHub's releases tab.

**Comment by KylieTastic** [comment]
Yup, never liked having that in the edit summaries

**Comment by enterprisey** [comment]
haha, works for me. guess we're CI/CD now. the version numbers were definitely from before my time. I just use deploy.py (although I've been intending to rewrite that), no release.py.
