### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by siddharthvp** [wikimedia-gadgets/afc-helper#283]
afch-rewrite is a very temporary sounding name. The rewrite was done nearly a decade ago, and the "beta" flag in the portlet menu was recently removed in #264. Let's just call this afc-helper now?

**Comment by NovemLinguae** [comment]
+1

Or `afc-helper-script`, or `afch`. Although I don't feel strongly about it, pick any of the three.

**Comment by NovemLinguae** [comment]
Related: The official gadget name that shows up in Special:Preferences is pretty long, `Yet Another AFC Helper Script`. But I was unable to get consensus to change that. There's a talk page thread somewhere where we discussed it. And maybe a ticket too. Having trouble finding them though.

**Comment by primefac** [comment]
in a semi-preferential order, I would go with `afc-helper`, `afch`, then `afc-helper-script`.

**Comment by siddharthvp** [comment]
Done - renamed to `afc-helper`.
