### ISSUE TITLE
add book and event to decline reasons

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#287]
Requested by Slgrandson at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#AFCH_may_be_in_need_of_two_new_decline-reason_codes

Add WP:NBOOK and WP:NEVENT to the notability declines list.

For both book and event:
* add them to https://github.com/wikimedia-gadgets/afc-helper/blob/4bef276b8e675ea50fbfa80aa9ea9d25b0c65af6/src/templates/tpl-submissions.html#L189-L199
  * [ ] book
  * [ ] event
* add them to https://en.wikipedia.org/wiki/Template:AfC_submission/comments (you can copy paste the text from "sport", and just change the SNG wikilink and a couple words). use a template editor edit request ({{TPER}}) on the talk page if you are not an admin or template editor
  * [x] book
  * [x] event
* add them to the above template's documentation page
  * [x] book
  * [x] event
* create categories, e.g. [[Category:AfC submissions declined as a non-notable X]]. these are used by the decline reasons
  * [x] book
  * [x] event

**Comment by anome2002** [comment]
I remeber requesting this in pull #266 , i am still able to work on this

**Comment by NovemLinguae** [comment]
Thanks. Will take a look at that pull request.
