### ISSUE TITLE
Improve deployment documentation

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#290]
Hey @enterprisey. I am trying to get the deploy script for AFCH to work, but I don't see an idiot-proof recipe anywhere. I started writing a recipe below. Would you be able to help fill in the blanks?

For Windows 11:
- download and install python 3
- open powershell as an administrator
- `cd [yourPathHere]/afc-helper/scripts`
- `python -m pip install pywikibot GitPython grunt parse`
    Note: These are installed globally by default, not per repo. In my case, they're downloaded to C:\Python311\Lib\site-packages
- `python upload.py en MediaWiki:Gadget-afchelper`

Getting the following error:

![image](https://github.com/wikimedia-gadgets/afc-helper/assets/79697282/1e1de9f1-e095-4beb-9972-d9d11a7923b0)

I also haven't typed my Wikipedia username and password anywhere. I imagine that needs to go in a file somewhere. Any ideas? Thanks.

**Comment by primefac** [comment]
Might want to check out https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Articles_for_creation/Helper_script/Contributing for additional thoughts.

**Comment by siddharthvp** [comment]
Dug around a bit. I think the missing steps are:
* Running `npm install`. grunt is not a pip package, it's an npm package. Also, the python script is ill-advisedly trying to run `grunt build` - which requires grunt to be installed globally (not a good idea as a different project you work on may want to use a different version of grunt). I suggest tweaking the script to run `npx grunt build` instead. (A workaround is to do `PATH=node_modules/grunt-cli/bin:$PATH` first).
* This script supports using either pywikibot or mwclient. To use mwclient, pass username as `--mwclient <username>` and it'll prompt for the password. With pywikibot, a user-config.py file would need to be created (refer [docs](https://www.mediawiki.org/wiki/Manual:Pywikibot/user-config.py)).
* Installing _any_ kind of python package globally is usually trouble. Always use a venv.

**Comment by sohomdatta1** [comment]
@siddharthvp @NovemLinguae I messed around with this for a bit and created a guide [at User:Sohom Datta/AFCH-Upload](https://en.wikipedia.org/wiki/User:Sohom_Datta/AFCH-Upload)
