### ISSUE TITLE
Accepted submissions with subject=dead and unknown death year are erroneously added to Category:Living people

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#293]
Reported by DreamRimmer on Discord

Steps to reproduce:
* find a draft
* click accept, the accept screen pops up
* tick biography
* type a birth date
* living or dead? select dead
* leave year of death blank
* accept
![image](https://github.com/wikimedia-gadgets/afc-helper/assets/79697282/0bbb35d5-4f65-44a3-8274-48e43555e9dc)

What happens?
* [[Category:Living people]]

What should have happened?
* no [[Category:Living people]]

Notes
* the bug involves [Template:L](https://en.wikipedia.org/w/index.php?title=Template:L&redirect=no) also known as [Template:Person categories](https://en.wikipedia.org/wiki/Template:Person_categories). This template is subst'd to determine what categories to place in the article. It cannot see the choice of the living/dead combo box, and if no death date is supplied, it will assume living.
* I think the simplest fix might be to modify Template:Person categories to accept "unknown" for the death date, then have AFCH pass "unknown" when unknown. We can add some code to the template to suppress Category:Living people if death date=unknown.
![image](https://github.com/wikimedia-gadgets/afc-helper/assets/79697282/eaacc499-b36b-421f-865c-8b1433a48362)

**Comment by sohomdatta1** [comment]
`UNKNOWN` or `MISSING` appears to be a already supported parameter input for the template L :)
