### ISSUE TITLE
deploy script adding strange unicode character

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#302]
https://en.wikipedia.org/w/index.php?title=MediaWiki:Gadget-afchelper.js/tpl-submissions.js&diff=prev&oldid=1184646437

This `Â` character is not in the repo, and should not be getting written when we run the deploy script. Bug in the deploy script?

@enterprisey thinks it may be because I am using Windows.

![image](https://github.com/wikimedia-gadgets/afc-helper/assets/79697282/dc5909fd-e658-431d-8940-863bc3147f46)

**Comment by NovemLinguae** [comment]
An error I get in the deploy console is the following. Maybe it's related?

```
Building afch-rewrite using `grunt build`...
OSError encountered. Attempting to use os.system...
```

![image](https://github.com/wikimedia-gadgets/afc-helper/assets/79697282/47cf3744-65c9-4107-9346-27a8d8c63468)

**Comment by sohomdatta1** [comment]
It definitely could be, the corrupt sequence ends with 0a which is known to be one of those sequences that has caused issues with Linux and Windows compatibility :(
