### ISSUE TITLE
when accepting a draft, user talk edit summary should wikilink to the draft, not to [[WP:AFC]]

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#305]
Reported by DoubleGrazing at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Link_in_notification

Steps to reproduce
* Accept a draft

What happens?
* User talk page of draft author is edited with the edit summary `Notification: Your [[Wikipedia:Articles for creation|Articles for creation]] submission has been accepted ([[Wikipedia:AFCH|AFCH]] 0.9.1)`

What should happen instead?
* User talk page of draft author is edited with the edit summary `Notification: Your [[Insert accepted article's title here|Articles for creation]] submission has been accepted ([[Wikipedia:AFCH|AFCH]] 0.9.1)`. This matches the decline and reject edit summaries, and provides more info to talk page watchers.

**Comment by sohelhussain** [comment]
Accept a draft
