### ISSUE TITLE
incorrect .git in package.json?

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#310]
Any idea why the below line in package.json says npm.git and not afc-helper.git? If we can't figure out why I may submit a patch to change it. Looks wrong to me.

```js
  "repository": {
    "type": "git",
    "url": "https://github.com/wikimedia-gadgets/afc-helper/npm.git"
  },
```

**Comment by siddharthvp** [comment]
Stems from https://github.com/wikimedia-gadgets/afc-helper/commit/0b54d9ff8e8470a5fa1bb474c3942ffd45b6480d (#87). But yes, it looks clearly wrong. `git clone https://github.com/wikimedia-gadgets/afc-helper/npm.git` rightfully fails with an error.
