### ISSUE TITLE
Implement WP:PIQA (put the article's class rating in the banner shell instead of in the wikiproject templates)

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#319]
https://en.wikipedia.org/wiki/Template:WikiProject_banner_shell/doc#Project-independent_quality_assessments

If a reviewer accepts an article and picks something such as class=start for it, this should be placed in the banner shell instead of in the individual WikiProject templates.

Good:

```
{{WikiProject banner shell |class=start |
{{WikiProject Tree of Life |importance=High}}
{{WikiProject Protista |importance=High}}
{{WikiProject Microbiology |importance=Mid}}
}}
```

Bad:

```
{{WikiProject banner shell|
{{WikiProject Tree of Life |class=start |importance=High}}
{{WikiProject Protista |class=start |importance=High}}
{{WikiProject Microbiology |class=start |importance=Mid}}
}}
```

**Comment by TechnoSquirrel69** [comment]
Note also that Military history needs to be specifically excluded; its banner should probably be left with an empty `|class=` parameter by default.

**Comment by NovemLinguae** [comment]
Mentioned at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Assigning_WikiProjects_to_Articles
