### ISSUE TITLE
Talk page headers rendering improperly

### ISSUE THREAD

**Issue by TechnoSquirrel69** [wikimedia-gadgets/afc-helper#333]
Thanks to everyone involved in #128! However, the section header needs to be added on a new line. As in [this diff](https://en.wikipedia.org/w/index.php?title=Talk:The_Black_Fish_(Keyan_Emami_album)&diff=prev&oldid=1218484590), AFCH is adding it on the same line as the WikiProject banner template, which causes it to render improperly.
![image](https://github.com/wikimedia-gadgets/afc-helper/assets/147560416/3c6269f4-5755-4988-8c2d-8718214f36b2)

**Comment by NovemLinguae** [comment]
Hotfix deployed. Thanks for reporting. The page in your diff was the only one affected, I think, according to https://en.wikipedia.org/w/index.php?search=%22Comments+left+by+AfC+reviewers%22&title=Special:Search&profile=advanced&fulltext=1&ns1=1
