### ISSUE TITLE
Can't F5 refresh browser when AFCH preferences dialog is open

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#344]
Steps to reproduce
- enable AFCH gadget
- go to a draft
- open AFCH
- click "preferences" to open preferences dialog
    - <img width="592" alt="image" src="https://github.com/wikimedia-gadgets/afc-helper/assets/79697282/0c420240-f482-45ea-8769-3d660eede123">
- press F5

What happens?
- nothing

What should happen instead?
- page refresh

Environment
- Chrome 123.0.6312.122 (Official Build) (64-bit)
- testwiki
- afch development version

Notes
- uses jqueryui.dialog: https://api.jqueryui.com/dialog/
- searches for F5, refresh, 116, keydown, onbeforeuload, and other keywords not turning up anything in the code

**Comment by primefac** [comment]
Cannot reproduce; F5 works as normal for me in the situation described above. Using Firefox beta.

**Comment by NovemLinguae** [comment]
Thanks for that info. Strangely I can no longer reproduce either. Closing for now.
