### ISSUE TITLE
should escape non-nested vertical bars in comments

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#358]
Requested by Squib at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Signature_wikicode_problem%3F

Something like [this](https://en.wikipedia.org/w/index.php?title=Draft:Adil_Raja&diff=prev&oldid=1218917862) should be checked by AFCH. If any vertical bars are found that aren't in nested templates, they should be changed to `{{!}}`, which is the proper escape character for these.

May also want to see if = instead of `{{=}}` causes the same bug.

May also want to add some unit tests for this. One equals non-nested, one equals nested, one vertical bar non-nested, one vertical bar nested.

Would probably need to run this escape function all over the place. AFCH places comments on the article itself for decline, reject, and comment operations, and also places comments on user talk pages for decline, reject, and comment operations.

**Comment by primefac** [comment]
See replies to that thread; reasonable concern has been raised that if we fix this issue (which is a known "do not do this" issue listed at WP:SIG) we're just covering up GIGO.
