### ISSUE TITLE
Submit button does not add timestamp to {{AfC submission}} template when {{AfC submission}} has no timestamp provided

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#362]
I had picked the default option in the dropdown. Example: https://en.wikipedia.org/w/index.php?title=Draft:Demolition_Ranch&diff=prev&oldid=1234778471

According to this warning, this seems to be incorrect. This is probably a bug in AFCH that needs fixing.

<img width="728" alt="image" src="https://github.com/user-attachments/assets/9676b4a7-8ef2-4ede-9252-7858409a9cfa">

Not sure if this is all the time, or just sometimes. See above diff for exact repro conditions, and then test some other stuff to see if it's all the time or sometimes.

**Comment by primefac** [comment]
That... shouldn't be happening, and I've never known a page with {{AfC submission/draft}} (which is what the |t param calls) to have that issue before. Maybe more extensive testing is needed?

**Comment by NovemLinguae** [comment]
Duplicate of #173
