### ISSUE TITLE
"Wikipedia:Articles for creation/recent" should include reviewer name and review datetime

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#367]
https://en.wikipedia.org/wiki/Wikipedia:Articles_for_creation/recent would be more useful if the reviewer name and review datetime were present. I'm using this log page today to make sure the latest AFCH patch isn't buggy and I noticed the absence of this data.

To fit this extra data, we should probably convert it from a bulleted list to a table with columns.

**Comment by primefac** [comment]
I'm not necessarily opposed, but we should make sure that there aren't any bots/dbase reports/etc that are using the page verbatim. Could probably still use [{{AfC contribution}}](https://en.wikipedia.org/wiki/Template:AfC_contribution) and just add two more parameters.

**Comment by KylieTastic** [comment]
I've always thought it should have the reviewer, don't really care on the datetime either way. Not sure how we could tell if anyone was using as primefac said unless you admins can see view logs.
