### ISSUE TITLE
Multiple WikiProject banners should be collapsed in {{WikiProject banner shell}}

### ISSUE THREAD

**Issue by Nathan2055** [wikimedia-gadgets/afc-helper#73]
At the moment any WikiProjects selected are simply stacked on the page, for readability reasons they should be collapsed in {{Wikiproject Shell Banner|1= }}.

**Comment by owcz** [comment]
Relatedly, the script currently duplicates banner additions when they're already in a WP banner shell on the talk page
https://en.wikipedia.org/w/index.php?title=Talk:Duane_Rousselle&type=revision&diff=944009379&oldid=925198061&diffmode=source

**Comment by NovemLinguae** [comment]
Note: There's also been a request to add the article class (such as start class) to the {{WikiProject banner shell}} template when a class is specified by the reviewer on the accept screen. Could be a good feature to add in after this ticket is completed.

**Comment by NovemLinguae** [comment]
Example: https://en.wikipedia.org/w/index.php?title=Talk:American_Embassy_School,_New_Delhi&oldid=1072862803
