### ISSUE TITLE
Add {{db-g3}} and {{db-g10}} options for submissions declined as vandalism

### ISSUE THREAD

**Issue by MER-C** [wikimedia-gadgets/afc-helper#91]
Vandal submissions should be considered for speedy deletion. See https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Articles_for_creation/Decline_comments_workshop#van

**Comment by josve05a** [comment]
Pinging this (vandalism should be moved from "decline" to "reject" as well).

**Comment by NovemLinguae** [comment]
Sorry, have to decline this one. The most recent discussion at WT:AFC did not achieve consensus for this feature.

https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Have_AFCH_allow_quick_CSD_tagging%3F
